### ISSUE TITLE
Plugin not working after EVE Praisal shutdown

### ISSUE THREAD

**Issue by jpeterek** [WipeOut-Inc/seat-buyback#14]
Hello, 

price check not working on EVEMarketer and EVEPraisal right now. 
is there a possiblity to add more services or get option to manualy setup evepraisal instance?

Thank you in advance,

**Comment by richieknight** [comment]
I too am now experiencing this problem since my Server was rebooted.
Everything is now showing as 0isk value when people are submitting contracts.
Eve Marketeer is set in the BuyBack options.

**Comment by H4zz4rdDev** [comment]
I have released version 1.3.2 today. You can set your evepraisal mirror url over the buyback admin settings now. I have removed EveMarketeer from the plugin
