### ISSUE TITLE
Blueprints missing from buy back options?

### ISSUE THREAD

**Issue by integratenate** [WipeOut-Inc/seat-buyback#6]
Hey there,

It looks like some blueprints are missing from the buy back options? Specifically some of the Triglavian BPCs? I tried looking for the Damavik blueprint and couldn't find it..

**Comment by H4zz4rdDev** [comment]
This has nothing to do with the plugin. The plugin is using the seat database. This database gets updated from time to time with new eve data. So if you are updating your whole seat installation all blueprints should be there. If not please provide the blueprints names that are missing
