### ISSUE TITLE
FEATURE: Add price to the list

### ISSUE THREAD

**Issue by martinskalicky** [WipeOut-Inc/seat-buyback#8]
Hello,

when we do process a lot of buybacks (20-30 daily) it might be really helpfull to see total price in the list without expanding the details.

So I would be able to see CODE and PRICE on the same ROW where i see ACCEPT buttons.

This would be really cool "life-hack".

Martin

**Comment by H4zz4rdDev** [comment]
Hey! Thx for the great idea. I have implemented that idea into the plugin. The final price will always be shown in the contract header of the contract overviews. This change will be published with version 1.3.0

![chrome_EUd6HkZc1W](https://user-images.githubusercontent.com/100998408/216823553-0cc4dac5-52e6-450f-8c0d-fe3b30d80abd.png)

**Comment by martinskalicky** [comment]
@H4zz4rdDev Any ETA on 1.3.0?

**Comment by martinskalicky** [comment]
Bump @H4zz4rdDev

**Comment by H4zz4rdDev** [comment]
@martinskalicky I hope I will finish version 1.3.0 in the next weeks. Have not much time to develop atm.
